from typing import Dict, Any, List
from sqlalchemy.orm import Session
from ..models.models import Rule, Alert, Endpoint
from ..repositories.repositories import RuleRepository, AlertRepository, EndpointRepository
import logging

logger = logging.getLogger("rules_engine")

class RulesEngine:
    @staticmethod
    def match_rule(telemetry_type: str, item: Dict[str, Any], rule: Rule) -> bool:
        # Check rule category match
        if rule.rule_type != telemetry_type:
            return False
            
        details = rule.details
        field = details.get("field")
        operator = details.get("operator")
        target_value = details.get("value")

        if not field or not operator:
            return False

        # Get actual value from the incoming item
        actual_value = item.get(field)
        if actual_value is None:
            return False

        # Convert values to strings or floats for comparison
        try:
            if operator == "equals":
                return str(actual_value).lower() == str(target_value).lower()
            elif operator == "contains":
                return str(target_value).lower() in str(actual_value).lower()
            elif operator == "greater_than":
                return float(actual_value) > float(target_value)
            elif operator == "less_than":
                return float(actual_value) < float(target_value)
        except Exception as e:
            logger.warning(f"Error executing rule matching: {e}")
            return False

        return False

    @classmethod
    def evaluate_telemetry(cls, db: Session, endpoint_id: str, telemetry_type: str, telemetry_data: List[Dict[str, Any]]) -> List[Alert]:
        active_rules = RuleRepository.list_active(db)
        matched_alerts = []

        endpoint = EndpointRepository.get_by_id(db, endpoint_id)
        if not endpoint:
            logger.warning(f"Evaluating telemetry for unknown endpoint: {endpoint_id}")
            return []

        for item in telemetry_data:
            for rule in active_rules:
                if cls.match_rule(telemetry_type, item, rule):
                    # Check if alert already exists for this process/file to prevent duplicates
                    existing = False
                    if telemetry_type == "Process":
                        process_name = item.get("name")
                        process_pid = item.get("pid")
                        existing = db.query(Alert).filter(
                            Alert.endpoint_id == endpoint_id,
                            Alert.process_name == process_name,
                            Alert.process_pid == process_pid,
                            Alert.alert_type == "Process",
                            Alert.title == rule.name,
                            Alert.status == "New"
                        ).first()

                    if not existing:
                        alert_data = {
                            "endpoint_id": endpoint_id,
                            "alert_type": telemetry_type,
                            "title": rule.name,
                            "description": f"Rule match occurred: {rule.description}. Technical match on {rule.details.get('field')} {rule.details.get('operator')} {rule.details.get('value')}",
                            "threat_score": 60 if rule.severity == "Medium" else (85 if rule.severity == "High" else 100),
                            "severity": rule.severity,
                            "status": "New",
                            "risk_explanation": f"This alert was automatically generated by the Rule: '{rule.name}' belonging to the group '{rule.rule_group}'. Check processes and network configurations for indicators of compromise.",
                            "process_name": item.get("name") if telemetry_type == "Process" else None,
                            "process_pid": item.get("pid") if telemetry_type == "Process" else None
                        }
                        alert = AlertRepository.create(db, alert_data)
                        matched_alerts.append(alert)
                        logger.info(f"Alert triggered: {alert.title} on endpoint {endpoint.hostname}")

        return matched_alerts
